#ALACRITTY CONFIG
background_opacity: 0.85
font:
  normal:
    family: Hack
    style: Regular

  bold:
    family: Hack
    style: Bold

  italic:
    family: Hack
    style: Italic

  bold_italic:
    family: Hack
    style: Bold Italic

  size: 10

selection:
  text: '0xffffff'
  background: '0xdc3232'
  white: '0xffffff'

cursor:
  style: Block
  unfocused_hollow: true

